### PR TITLE
Initial commit and creation of dnanexus file structure

### PR DESCRIPTION
**Pull request by Graeme-Smith**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/5)

### CODE REVIEW

**Comment by aledj2** [comment]
I haven't tried it but the merge_vcf_header seems quite complex, could you not just use sed, with the expected header line (starting with single # ) as this doesn't change (if all sample names are '1'?)

---

Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 1 of 1 files at r4.
Review status: 3 of 5 files reviewed at latest revision, 18 unresolved discussions.

---

*[Readme.md, line 9 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PbHBXyxBK4bE9t-Rl:-L0PbHBXyxBK4bE9t-Rm:b-a7sshg) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L9)):*
> ```Markdown
> 
> ## What are typical use cases for this app?
> This app should be performed after each run. It can be run automagically using the --depends-on flag or manually.
> ```

The app should be run after workflows for all samples in a run complete successfully. This is scheduled by the upload agent script using --depends-on flag or can be triggered manually

The output is displayed in multiqc

Why is this app used? eg Peddy is used to detect when the sex doesn't match ...etc

---

*[Readme.md, line 14 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PbfHy4ptwjq_fwYEK:-L0PbfHy4ptwjq_fwYEL:b-6hdrub) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L14)):*
> A project number is passed to the app as a parameter.
> This project must have a folder 'QC' within the root of the project.
> The filename of each sample must include the gender as 'M' or 'F' deliminated by underscores.

Can we make these bullet points?
What files are downloaded from the QC folder?

---

*[Readme.md, line 34 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PfE2i7OKWJ4Fhxkid:-L0PfE2i7OKWJ4Fhxkie:b-ak6vye) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L34)):*
> ## What does this app output?
> Several files prefixed with 'ped.' are produced. MultiQC uses 4 of these files:
> 1. ped.peddy.ped
> 2. ped.het_check.csv
> 3. ped.ped_check.csv
> 4. ped.sex_check.csv
>  
> Files 1-4 are placed in /QC/. The remaining files are unused by the pipeline:
>  
> 5. ped.background_pca.json
> 6. ped.het_check.png
> 7. ped.html
> 8. ped.pca_check.png
> 9. ped.ped_check.png
> 10. ped.ped_check.rel-difference.csv
> 11. ped.sex_check.png
> 12. ped.*project_name*.fam
>  
> Files 5-12 are placed in /QC/peddy_extra/

all output files are prefixed with ped.

MultiQC requires 4 files:
1.
2. ...

These files are output to /QC/

the remaining files are put into a subfolder /QC/peddy_extra (can we rename this folder to /QC/peddy?) (I don't think there's any need to list them unless specify what each file contains) 

---

*[Readme.md, line 37 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PfNzQTJwqOJ88D6us:-L0PfNzRg66vslcXv4oo:b-n14ghr) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L37)):*
> It then creates a merged vcf from the run's
(new bullet point) * All VCF files are merged into a multisample VCF
(new bullet point) * peddy is run using the fam file and multisample VCF
(new bullet point) * The output is saved into /QC/

---

*[Readme.md, line 37 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PhISkBl2W3TvT30__:-L0PhISkBl2W3TvT30_a:buc0mzw) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L37)):*
> in /QC/multiqc
I don't think multiQC looks in QC/multiQC - that's where the multiqc output goes

---

*[Readme.md, line 40 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Phe65FFFdJlo7KBfg:-L0Phe65FFFdJlo7KBfh:b-32jm2o) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L40)):*
> ```Markdown
> 
> ## What are the limitations of this app
> The degree of functionality that peddy provides depends upon the metadata available. 
> ```

what does this line mean?

---

*[Readme.md, line 42 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PhrUuk0lfYPoL80mH:-L0PhrUuk0lfYPoL80mI:b-afsjkx) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L42)):*
> Requires bcftools to be installed on the server.
> Requires peddy (https://github.com/brentp/peddy).
These are determined in the app so aren't needed to be stated

---

*[resources/home/dnanexus/readme.txt, line 1 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PZFVmdoyJ5EMIycrr:-L0PZFVmdoyJ5EMIycrs:bxx5xxe) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/resources/home/dnanexus/readme.txt#L1)):*
> ```
> This directory resources/home/dnanexus/ is where the auth_key will be stored when the app is packaged for DNAnexus.
> ```

BTW is this file needed? (it does no harm)

---

*[src/code.sh, line 50 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PmP0QnSDT9j9qyDrl:-L0PmP0QnSDT9j9qyDrm:btf93ao) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L50)):*
> ```Shell
>     # where '%%' deletes the longest match of 'substring' from the end of $string.
>     # This is required as Peddy does not accept '.' characters in sample names. 
>     echo ${1%%\.*} > $tmp
> ```

can you explain {1%%\.*} please

---

*[src/code.sh, line 52 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PmfBchLPuCVw3TnlS:-L0PmfBchLPuCVw3TnlT:blh7rhl) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L52)):*
> ```Shell
>     echo ${1%%\.*} > $tmp
>     # Use bcftools to change sample name in vcf header to match file name
>     bcftools reheader -s $tmp $1 > temp.$1
> ```

what is $1? 
what is this line doing?

---

*[src/code.sh, line 53 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PmofohfJ2mo2sqKaK:-L0PmofohfJ2mo2sqKaL:b-tamg28) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L53)):*
> ```Shell
>     # Use bcftools to change sample name in vcf header to match file name
>     bcftools reheader -s $tmp $1 > temp.$1
>     mv temp.$1 $1
> ```

what was the need for temp files?

---

*[src/code.sh, line 75 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkjlqYTNOZ57gUonw:-L0PkjlqYTNOZ57gUonx:boqph9v) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L75)):*
> ```Shell
>     fam_file="ped.${project_for_peddy}.fam"
>     # Create empty fam file. The null operator (:) is redirected to a file, named using $fam_file.
>     # This ensures an empty FAM file is created for writing to, even if it already exists
> ```

would this ever be the case? could you not just use touch?

---

*[src/code.sh, line 83 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkxYEMVxAMzoP_CC1:-L0PkxYEMVxAMzoP_CC2:b-pupnzq) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L83)):*
> ```Shell
>     for file in *vcf.gz; do
>         # Extract sample sex from file name
>         sex=$(echo $file | sed -n 's/.*_\([M,F]\)_.*/\1/p')
> ```

can you describe this a bit more please. what about unknown sex? (see other comment below)

---

*[src/code.sh, line 89 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Pl7fueqDP43g69ksb:-L0Pl7fueqDP43g69ksc:b-7bx0kj) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L89)):*
> if [[ $sex == "M" ]]; then
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>             sex_code="1"
>         elif [[ $sex == "F" ]]; then
>             sex_code="2"
>         else
>             sex_code="0" #Unknown sex
>         fi
</details>

BTW what if the gender is missing from the file name? should the app fail or should we assume sex is unknown?

---

*[src/code.sh, line 99 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PlgNnK0zjcNLWbddk:-L0PlgNnK0zjcNLWbddl:bpys8ku) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L99)):*
> ```Shell
>         fam_ID=$((fam_ID+1))
>         # Write out line to FAM file in tab delimited format
>         echo -e "FAM$fam_ID\t$sample_name\t0\t0\t$sex_code\t2" >> $fam_file
> ```

what is the last 2? phenotype?

---

*[src/code.sh, line 121 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkIzY_BN0nTAGizpt:-L0PkIzY_BN0nTAGizpu:b-sf2u4z) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L121)):*
> ```Shell
> # Download the desired inputs. Use the input $project_for_peddy to build the path to look in.
> dx download $project_for_peddy:output/*.refined.vcf.gz --auth $API_KEY
> dx download $project_for_peddy:output/*vcf.gz.tbi --auth $API_KEY
> ```

shouldn't you also be getting the refined vcf index? the non-refined vcf index is for a different (unannotated vcf file)

---

*[src/code.sh, line 128 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Plt8fv4Hx_1pPINAO:-L0Plt8fv4Hx_1pPINAP:b-h3dv06) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L128)):*
> create_fam_file
> batch_rename_vcf_header
> merge_vcfs 
can you comment what each step does (briefly) to easily see what is done without  going up and down the script

---

*[src/code.sh, line 137 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Pi6bgyZg_30dCKVWg:-L0Pi6bgyZg_30dCKVWh:b8ur8s9) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L137)):*
> peddy_extra
sorry could we call this folder peddy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-:-L0PnyB-ON6OUfykciTo:b-a4zv3o)*

**Comment by Graeme-Smith** [comment]
*[resources/home/dnanexus/readme.txt, line 1 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PZFVmdoyJ5EMIycrr:-L0PteGR-cZESHu9FIPv:bsf9p07) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/resources/home/dnanexus/readme.txt#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

BTW is this file needed? (it does no harm)
</blockquote></details>

I created a read.me file in this folder so that I could create the folder structure in git.  As far as I'm aware git ignores empty folders when pushing to the remote - this was the easiest way of getting git to duplicate the folder structure I had on my local machine on github.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5)*

**Comment by Graeme-Smith** [comment]
*[Readme.md, line 14 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PbfHy4ptwjq_fwYEK:-L0Q3DeWkjK2LBRNQYxj:bi6eh6n) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L14)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> A project number is passed to the app as a parameter.
> This project must have a folder 'QC' within the root of the project.
> The filename of each sample must include the gender as 'M' or 'F' deliminated by underscores.

Can we make these bullet points?
What files are downloaded from the QC folder?
</blockquote></details>

I've converted these to bullet points and added *refined.vcf.gz and *refined.vcf.gz.tbi as the files downloaded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5)*

**Comment by Graeme-Smith** [comment]
*[Readme.md, line 40 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Phe65FFFdJlo7KBfg:-L0Q8aonlodpRoqJT1vM:b3fxex0) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L40)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what does this line mean?
</blockquote></details>

I've deleted this line - when I started writing this code I was unsure where the sample sex would come from and whether we would have metadata outlining which samples are related.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5)*

**Comment by NMNS93** [comment]
Review status: 3 of 5 files reviewed at latest revision, 18 unresolved discussions.

---

*[Readme.md, line 9 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PbHBXyxBK4bE9t-Rl:-L0fdNdhuEOSPSkin08_:b-rpy50o) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L9)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

The app should be run after workflows for all samples in a run complete successfully. This is scheduled by the upload agent script using --depends-on flag or can be triggered manually

The output is displayed in multiqc

Why is this app used? eg Peddy is used to detect when the sex doesn't match ...etc
</blockquote></details>

Added description of what peddy does to help with reading output. 

---

*[Readme.md, line 14 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PbfHy4ptwjq_fwYEK:-L0fdl9_6PXUTJ3D5CmV:b-ls96iv) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L14)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I've converted these to bullet points and added *refined.vcf.gz and *refined.vcf.gz.tbi as the files downloaded.
</blockquote></details>

I think this may not have been committed? Added regardless

---

*[Readme.md, line 34 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PfE2i7OKWJ4Fhxkid:-L0fdvusST4kOTcO1b11:bsdgxqm) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L34)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ## What does this app output?
> Several files prefixed with 'ped.' are produced. MultiQC uses 4 of these files:
> 1. ped.peddy.ped
> 2. ped.het_check.csv
> 3. ped.ped_check.csv
> 4. ped.sex_check.csv
>  
> Files 1-4 are placed in /QC/. The remaining files are unused by the pipeline:
>  
> 5. ped.background_pca.json
> 6. ped.het_check.png
> 7. ped.html
> 8. ped.pca_check.png
> 9. ped.ped_check.png
> 10. ped.ped_check.rel-difference.csv
> 11. ped.sex_check.png
> 12. ped.*project_name*.fam
>  
> Files 5-12 are placed in /QC/peddy_extra/

all output files are prefixed with ped.

MultiQC requires 4 files:
1.
2. ...

These files are output to /QC/

the remaining files are put into a subfolder /QC/peddy_extra (can we rename this folder to /QC/peddy?) (I don't think there's any need to list them unless specify what each file contains) 
</blockquote></details>

Updated to acknowledge outputs to QC/peddy. Removed list of the extra files.

---

*[Readme.md, line 37 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PfNzQTJwqOJ88D6us:-L0fe25iwuRimuSHJz3_:bf7l8r2) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/Readme.md#L37)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> It then creates a merged vcf from the run's
(new bullet point) * All VCF files are merged into a multisample VCF
(new bullet point) * peddy is run using the fam file and multisample VCF
(new bullet point) * The output is saved into /QC/
</blockquote></details>

Bullet-pointed the app procedure

---

*[src/code.sh, line 50 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PmP0QnSDT9j9qyDrl:-L0feJs5dk6MSUqmgK7D:b5zmbc4) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L50)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you explain {1%%\.*} please
</blockquote></details>

Assigned $1 to a more explicit variable and added explanations of usage. The filename parsing step that used this has been moved to the function 'get_sample_name'

---

*[src/code.sh, line 52 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PmfBchLPuCVw3TnlS:-L0fekiAnVGijEaKlVdj:b-q64pl6) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L52)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what is $1? 
what is this line doing?
</blockquote></details>

See above!

---

*[src/code.sh, line 53 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PmofohfJ2mo2sqKaK:-L0ferWgEH9HgCqqXcua:b-bv7xmp) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L53)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what was the need for temp files?
</blockquote></details>

Added explanation. See comment for rename_vcf_header (the block of text after the usage string).
It is because bcftools takes the new sample names from a file, not from the command line.

**Also sometimes not sure if these questions are to be addressed by adding comment to code or in reviewable? Any convention for this? **

---

*[src/code.sh, line 75 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkjlqYTNOZ57gUonw:-L0ffmUenhNjQLaE8e-F:b79fn80) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L75)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

would this ever be the case? could you not just use touch?
</blockquote></details>

Changed to touch; used the null thing as I was re-running this function locally while testing but realise now overwrites wouldn't be a problem for the worker.

---

*[src/code.sh, line 83 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkxYEMVxAMzoP_CC1:-L0ffyaVX3qX_2SdOdx6:b-xs8ew4) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L83)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you describe this a bit more please. what about unknown sex? (see other comment below)
</blockquote></details>

Added description, is this clearer?

---

*[src/code.sh, line 89 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Pl7fueqDP43g69ksb:-L0fg4mZOWqFWerteMlx:b8ks1u5) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L89)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> if [[ $sex == "M" ]]; then
>             sex_code="1"
>         elif [[ $sex == "F" ]]; then
>             sex_code="2"
>         else
>             sex_code="0" #Unknown sex
>         fi

BTW what if the gender is missing from the file name? should the app fail or should we assume sex is unknown?
</blockquote></details>

Currently if the gender is missing, the sex code for the sample is set to 0 and the app assumes sex is unknown. I don't think failing in this event makes sense as the app can then be run on 'legacy' filenames without breaking. It just wouldn't be informative of sample sex.

---

*[src/code.sh, line 99 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PlgNnK0zjcNLWbddk:-L0fgOs7M0OVRTd7jYMU:b5rocgf) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L99)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what is the last 2? phenotype?
</blockquote></details>

I think it was generic phenotype but removed as app runs fine without and it's optional

---

*[src/code.sh, line 121 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkIzY_BN0nTAGizpt:-L0fgUXmbnXCJjGDYkO3:bwjybie) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L121)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

shouldn't you also be getting the refined vcf index? the non-refined vcf index is for a different (unannotated vcf file)
</blockquote></details>

Realised actually, no index file is required from the project, just the VCF. We created the indexes for the individual VCF files and the merged vcf using bcftools.

---

*[src/code.sh, line 128 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Plt8fv4Hx_1pPINAO:-L0fgfvK6vo6yhTYSQd-:b-du2m31) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L128)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> create_fam_file
> batch_rename_vcf_header
> merge_vcfs 
can you comment what each step does (briefly) to easily see what is done without  going up and down the script
</blockquote></details>

Added comment for each process. Let me know if clear.

---

*[src/code.sh, line 137 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0Pi6bgyZg_30dCKVWg:-L0fgkndvuux-Yfv2IqY:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L137)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> peddy_extra
sorry could we call this folder peddy?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5)*

**Comment by aledj2** [comment]
a nice script!! very minor tweaks.

---

Reviewed 1 of 2 files at r8.
Review status: 4 of 5 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/code.sh, line 83 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L0PkxYEMVxAMzoP_CC1:-L1MfWyD-UVec-ymy3NY:b-f1fa8y) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/69cf6e39e04460f3a978f596f33f1d2786b06290/src/code.sh#L83)):*
<details><summary><i>Previously, NMNS93 (Nana E. Mensah) wrote…</i></summary><blockquote>

Added description, is this clearer?
</blockquote></details>

sorry, could you explain the regex a bit more, eg why the round and square brackets. why the full stop either side of the underscores (inside the *'s).
also what does the back-reference capture/work?

---

*[src/code.sh, line 21 at r8](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L1MbVID3pUir1z_lH2A:-L1MbVID3pUir1z_lH2B:b-dbmf6j) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/33e899f812cc33d4ee66abc104e003493e5a2341/src/code.sh#L21)):*
> ocation
location

---

*[src/code.sh, line 27 at r8](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L1MbcaKMroddk52B3kO:-L1MbcaKMroddk52B3kP:b-q3j2b1) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/33e899f812cc33d4ee66abc104e003493e5a2341/src/code.sh#L27)):*
> ```Shell
>     conda config --add channels bioconda
>     # Install bcftools and peddy
>     conda install -y bcftools peddy
> ```

is it worth specifying the versions to download incase they are updated and require different inputs? 

---

*[src/code.sh, line 117 at r8](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L1MfTrUm2P0DTcplH25:-L1MfTrV2kJJnMcpRcIm:b-c9389n) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/33e899f812cc33d4ee66abc104e003493e5a2341/src/code.sh#L117)):*
> whic
which

---

*[src/code.sh, line 176 at r8](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-L1MhPOnhLBBrosCPE9C:-L1MhPOnhLBBrosCPE9D:b-x28iq0) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/33e899f812cc33d4ee66abc104e003493e5a2341/src/code.sh#L176)):*
> fromm
from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-:-L1MiOWe42T2HriRBOOy:b-jtspco)*

**Comment by NMNS93** [comment]
Reviewed 1 of 2 files at r8.
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r9.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5#-:-L2LIPNEvvvVj-zRg7Sp:bnfp4nl)*

**Comment by aledj2** [comment]
Reviewed 1 of 2 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/5)*

**Pull request merged**
