### PR TITLE
Bugfix 180518

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14)

### CODE REVIEW

**Comment by AmyAmelia** [comment]
+@amyamelia 

---







*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14#-:-LCmvmxl4d73v1fpQJ1z:b-z3lu1q)*

**Comment by AmyAmelia** [comment]
*[Readme.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14#-LCmwjovEIYevo5hS8HW:-LCmwjovEIYevo5hS8HX:bxdsez7) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/feca77daa162e80e6a4add3931a95fa8a249fc02/Readme.md#L4)):*
> ```Markdown
> 
> ## What does this app do?
> This app runs peddy v0.3.1 (https://github.com/brentp/peddy) to perform a run wide QC check that the assigned gender matches the sample. This app uses a release of peddy from https://github.com/moka-guys/peddy.
> ```

Is this still the case?

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14)*

**Comment by AmyAmelia** [comment]
*[src/code.sh, line 59 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14#-LCmxaJ_EpzzCd80bSWY:-LCmxaJ_EpzzCd80bSWZ:bxfcnqi) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/feca77daa162e80e6a4add3931a95fa8a249fc02/src/code.sh#L59)):*
> ```Shell
>     echo ${new_sample_name} > $tmp
> 
>     # Use bcftools to rename the sample name in vcf header, using the sample name in the temp file.
> ```

might be worth adding the bedtools version to comments. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14)*

**Comment by andyb3** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Readme.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14#-LCmwjovEIYevo5hS8HW:-LCmzV_L0Lr-K_iRjoVB:besygtc) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/feca77daa162e80e6a4add3931a95fa8a249fc02/Readme.md#L4)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

Is this still the case?
</blockquote></details>

Nope it is not! 
Done

---

*[src/code.sh, line 59 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14#-LCmxaJ_EpzzCd80bSWY:-LCn-Mn-8i2AdzKFFT-P:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/feca77daa162e80e6a4add3931a95fa8a249fc02/src/code.sh#L59)):*
<details><summary><i>Previously, AmyAmelia wrote…</i></summary><blockquote>

and that its is a Docker container (like you have done for peddy)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14)*

**Comment by AmyAmelia** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/14#-:-LCn0U99CZgkXRjgVcbD:bnfp4nl)*

**Pull request merged**
