### PR TITLE
Install peddy and bcftools. Upload peddy outputs. fix #1 #4

### LINKED ISSUE #1: Add bcftools installation to code.sh
bcftools is required to rename vcf headers and merge vcf files for use with peddy.

### PR DESCRIPTION
**Pull request by NMNS93**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_peddy/7)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/code.sh, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bmx7KPJtzKl8FZy1_:-L-bmx7KPJtzKl8FZy1a:br42cok) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L44)):*
> ```Shell
> function rename_vcf_header {
>     # Use mktemp to create a temp file
>     tmp=$(mktemp -t temp.XXX)
> ```

What  does this addition do?

---

*[src/code.sh, line 47 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bqCMiJ1xxiUUwpm-1:-L-bqCMj1r88giOLVMA8:bm0fwsl) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L47)):*
> ```Shell
>     # Copy vcf file name called by function into temp file. VCF file extension is removed using
>     # ${string%%substring}, where '%%' deletes the longest match of 'substring' the end of $string
>     echo ${1%%\.*} > $tmp
> ```

So if I understand correctly this deletes all file extension suffixes from the file names? If the files are suffixed `.vcf.gz` or `. vcf` it will remove them just leaving the filename?  Maybe mention in the notes that this is required as peddy throws a wobbly if the sample names in the merged vcf contain the extension.

---

*[src/code.sh, line 56 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bo7e8ojiEKkgK8DFs:-L-bo7e8ojiEKkgK8DFt:b-3wzs67) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L56)):*
> ```Shell
> }
> 
> # Run rename_vcf_header function on all vcf files in the working directory (/home/dnanexus)
> ```

Would it be better to ensure this explicitly?  For example:

```bash
 for files in /home/dnanexus/*.vcf.gz
```


---

*[src/code.sh, line 68 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bkucDXqfmTO7Fs-5l:-L-bkucDXqfmTO7Fs-5m:bnisko) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L68)):*
> ```Shell
> #     Family_ID [string], Individual_ID [string], Father_ID [string], 
> #     Mother_ID [string], Sex [integer], Phenotype (optional) [float]
> # Note: Father_ID, Mother_ID, or Sex of 0 = Unknown
> ```

Maybe also mention that individual ID cannot be 0.  
Also would it be better written like:

```bash
#     Family_ID [string] \t Individual_ID [string] \t Father_ID [string] \t
#     Mother_ID [string] \t Sex [integer] \t Phenotype (optional) [float]
```
to make the fact it is a tab delimited file explicit.

---

*[src/code.sh, line 74 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bouMdHHSf35AeqBsG:-L-bouMeRur5O0RAE3I3:b-x87a3b) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L74)):*
> ```Shell
>     # Create empty fam file. The null operator (:) is redirected to a file, named using $fam_file.
>     # This ensures an empty FAM file is created for writing to, even if it already exists
>     :> $fam_file
> ```

I like this. :+1: 

---

*[src/code.sh, line 94 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bfgE3jLhkVEDz-9l2:-L-bfgE3jLhkVEDz-9l3:b7botip) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L94)):*
> ```Shell
>         # `cat/dev/urandom` creates a pseudo-random stream of characters, which is limited to alpha-
>         # numeric characters using `tr -dc '[:alnum:]', and limited to 10 characters using `head -c 10`
>         famid=$(echo $(cat /dev/urandom | tr -dc '[:alnum:]' | head -c 10))
> ```

What is the advantage of using a randomly generated string as the family ID?

For peddy to perform a sex check or identify duplicate samples we simply need the Family ID to be a unique identifier - so we don't accidentally allocate two people to the same family. 

This could be accomplished by:
1. Using the line number of the row in the fam file.
1. Using the sample number from the file name.

Would the code for either of these be more readable?

---

*[src/code.sh, line 111 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-btQOiuSxVVRS7B2Tu:-L-btQOjNBOGJHmlg-vy:bmi8ppe) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L111)):*
> ```Shell
> ############### Run Program ###############
> 
> main(){
> ```

:100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7)*

**Comment by Graeme-Smith** [comment]
*[src/code.sh, line 71 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-fDFDxKL1pEQvelAv2:-L-fDFDxKL1pEQvelAv3:b-3zi4q4) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L71)):*
> ```Shell
> function create_fam_file {
>     # Set string with FAM file name using project folder title
>     fam_file="ped.${project_for_peddy}.fam"
> ```

Would it be better to use an _ as the first deliminator to have consistent formatting?

```bash
 fam_file="ped_${project_for_peddy}.fam"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7)*

**Comment by Graeme-Smith** [comment]
*[src/code.sh, line 71 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-fDFDxKL1pEQvelAv2:-L-fNEgufLZtatJDEL5l:b-izcw7q) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L71)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Would it be better to use an _ as the first deliminator to have consistent formatting?

```bash
 fam_file="ped_${project_for_peddy}.fam"
```
</blockquote></details>

FYI Also the Readme.md will need amending to reflect the name of the file being created.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7)*

**Comment by NMNS93** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/code.sh, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bmx7KPJtzKl8FZy1_:-L-gHDL_AdPSmHfTZFJG:b-rerpng) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L44)):*
mktemp raised an error because the command expects a temporary file with a minimum of three X's, from manual:

> The mktemp utility takes the given filename template and overwrites a portion of it to create a unique filename. 
> The template may be any filename with some number of ‘Xs’ appended to it, for example /tmp/tfile.XXXXXXXXXX

### Does this need a comment? At the time I wasn't sure.

---

*[src/code.sh, line 47 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bqCMiJ1xxiUUwpm-1:-L-gJaI8DKrEd_oeMI-n:b-7t5lbn) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L47)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

So if I understand correctly this deletes all file extension suffixes from the file names? If the files are suffixed `.vcf.gz` or `. vcf` it will remove them just leaving the filename?  Maybe mention in the notes that this is required as peddy throws a wobbly if the sample names in the merged vcf contain the extension.
</blockquote></details>

Correct, this will remove the first '.' character  and everything following it from the file name. I have updated this comment in the latest commit!

---

*[src/code.sh, line 56 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bo7e8ojiEKkgK8DFs:-L-gMfanwjy936Z0NOYs:bkw3c1l) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L56)):*
I wasn't sure about hard-coding the directory, tried it with $HOME as it achieves the same thing but using a variable.
This caused an error as it then passes:
> rename_vcf_header /home/dnanexus/file.vcf.gz

Instead of:

> rename_vcf_header file.vcf.gz

So I've left it as it is - **Is it worth a comment?**

---

*[src/code.sh, line 68 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bkucDXqfmTO7Fs-5l:-L-gbCEh_qTB9hwX-lW1:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L68)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Maybe also mention that individual ID cannot be 0.  
Also would it be better written like:

```bash
#     Family_ID [string] \t Individual_ID [string] \t Father_ID [string] \t
#     Mother_ID [string] \t Sex [integer] \t Phenotype (optional) [float]
```
to make the fact it is a tab delimited file explicit.
</blockquote></details>

Done.

---

*[src/code.sh, line 71 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-fDFDxKL1pEQvelAv2:-L-gbKTYeLvpi-fnAZWe:b-i87k0c) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L71)):*
Chose to do this because the peddy output files have the same convention, e.g.: 

> ped.het_check.csv
> ped.ped_check.csv
> ped.peddy.ped
> ped.sex_check.csv

So having the FAM file `ped.runfolder.fam` is consistent, even though dots should be reserved for extensions, will ammend Readme to reflect this

---

*[src/code.sh, line 74 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bouMdHHSf35AeqBsG:-L-geEm5AOCspnM2vT2c:b-txoim5) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L74)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I like this. :+1: 
</blockquote></details>

:1st_place_medal: 

---

*[src/code.sh, line 94 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-L-bfgE3jLhkVEDz-9l2:-L-gg30q_OmjCbTRs4o3:b798eiz) ([raw file](https://github.com/moka-guys/dnanexus_peddy/blob/d1ada1af96ec104d62a686ce8625491fbe3f721a/src/code.sh#L94)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

What is the advantage of using a randomly generated string as the family ID?

For peddy to perform a sex check or identify duplicate samples we simply need the Family ID to be a unique identifier - so we don't accidentally allocate two people to the same family. 

This could be accomplished by:
1. Using the line number of the row in the fam file.
1. Using the sample number from the file name.

Would the code for either of these be more readable?
</blockquote></details>

Wonderful point, changed to a number counting for each line of the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7)*

**Comment by Graeme-Smith** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7#-:-L-kIngW0tTBtRh-i4ZY:bnfp4nl)*

**Comment by Graeme-Smith** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_peddy/7)*

**Pull request merged**
